"""empty message

Revision ID: d452c9f8fec1
Revises: 
Create Date: 2019-04-11 11:18:43.445094

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd452c9f8fec1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('filehash', table_name='PasteFile')
    op.drop_table('PasteFile')
    op.add_column('login_users', sa.Column('email', sa.String(length=128), nullable=False))
    op.add_column('login_users', sa.Column('password', sa.String(length=256), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('login_users', 'password')
    op.drop_column('login_users', 'email')
    op.create_table('PasteFile',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('filename', mysql.VARCHAR(length=5000), nullable=False),
    sa.Column('filehash', mysql.VARCHAR(length=128), nullable=False),
    sa.Column('filemd5', mysql.VARCHAR(length=128), nullable=False),
    sa.Column('uploadtime', mysql.DATETIME(), nullable=False),
    sa.Column('mimetype', mysql.VARCHAR(length=256), nullable=False),
    sa.Column('size', mysql.INTEGER(display_width=11, unsigned=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index('filehash', 'PasteFile', ['filehash'], unique=True)
    # ### end Alembic commands ###
